### ISSUE TITLE
ran into error

### ISSUE THREAD

**Issue by Huanle** [OrensteinLab/SWOffinder#4]
Hi @ofiryaish ,

thank you and your colleagues for developing this valuable tool for the community.

I'd love to give it a go. But I ran into errors.

The command I used: 
'''
java -cp bin SmithWatermanOffTarget.SmithWatermanOffTargetSearchAlign test/mouse.fa test/h82_h65 \
        vs_mouse \
        4 4 3 1 \
        10 \
        true \
        23 \
        NGG true
'''

java version: java 21.0.1 2023-10-17 LTS
I tried openjdk17 as well, but the errors remained. 

The error I came across:
Saved sequence chr1_1 to file /home/designer/sw/toolkits/SWOffinder/test/mouse_split/chr1_1.txt
...
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
...

I hope this is enough for you to help me figure out the underlying cause of this error.
Thanks a lot.

**Comment by ofiryaish** [comment]
Hi @Huanle

Thank you for trying to use the tool.

If you provide me with the complete error log, I might figure out where the error occurred. Could you do that, please?

In addition, if you can and want, please share the sgRNA list (test/h82_h65) and the genome reference (test/mouse.fa) or part of it if it is too big (to understand its format). You can also send it privately to yaishof@post.bgu.ac.il.

I will also try to add an example of a simple run using the tool in the following days. 

Thank you again for raising this,
Ofir

**Comment by Huanle** [comment]
Hi @ofiryaish ,
Thanks a lot for your prompt response. 
We found that this error was caused by the gRNA list file name without a '.' in it. 
After renaming `h82_h65` to `gRNA.txt`. It worked.

So maybe you would love to slightly modify the relevant codes to avoid such kind of failures.

Thanks again.

**Comment by ofiryaish** [comment]
@Huanle 

Thank you for your update. I will look into what can be done so that other users don't encounter this problem again.

Please let us know if you encounter other problems, and thank you again for letting us know!
